blank_issues_enabled: false
contact_links:
  - name: ‚ú® Feature Request
    url: https://github.com/bcakmakoglu/vue-flow/discussions/new
    about: Have an idea for a new feature? Share it here!
  - name: ‚ùì Ask a Question
    url: https://github.com/bcakmakoglu/vue-flow/discussions/new
    about: If you have any questions about how to do something with Vue Flow, ask it here.
  - name: ü§ù Discord
    url: https://discord.gg/z4FMpfTugW
    about: Join the Discord server to chat with the community.
